[build]
  command = "npm run build" # Your actual build command
  publish = "_site"         # The directory Jekyll outputs your site to (usually _site)

[context.production]
  # Environment variables you set in Netlify UI (ONESIGNAL_APP_ID, ONESIGNAL_REST_API_KEY)
  # will automatically be available to your build process and scripts.

  # This command runs AFTER your main 'command' (npm run build) completes successfully.
  # The '&&' ensures the script only runs if the main build was successful.
  post_build = "node ./push.js"
  